version: '3'
services:
  web:
    build:
      context: ./docker/web
    image: isucon-web
    depends_on:
      - app
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./docker/web/isucon.conf /etc/nginx/sites-available/isucon.conf

  app:
    build:
      context: ./docker/app
    image: isucon-app:golang
    tty: true
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "1323"
    volumes:
      - document_root:/home/isucon/isuumo/webapp
    environment:
      MYSQL_DBNAME: isuumo
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      GOPATH: /home/isucon/isuumo/webapp/go/

  db:
    build:
      context: ./docker/db
    image: isucon-db
    networks:
      - backend
    ports:
      - "3306"
    command: ["--character-set-server=utf8mb4,--sql_mode=NO_ENGINE_SUBSTITUTION"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: isuumo
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon

networks:
  frontend:
  backend:

volumes:
  document_root:
    driver_opts:
      type: none
      device: /home/jp_taku/work/isucon-10-qualify/isuumo/webapp
      o: bind
